name: Launch build of development conda packages of SOFA
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-slim
    if: ${{ github.repository_owner == 'sofa-framework' }}

    steps:
      # first extract SOFA and SofaPython3 last commit sha and date on their resp
      # master branches, which be used as ref for building the devel conda packages
      - uses: actions/checkout@v4
      - name: Get SOFA commit date
        run: |
          SOFA_COMMIT_DATE=$(git show -s --date=format:%Y%m%d --format=%cd ${{ github.sha }})
          echo "SOFA_COMMIT_DATE=$SOFA_COMMIT_DATE" >> $GITHUB_ENV

      - name: Checkout SOFA Python3
        uses: actions/checkout@v4
        with:
          repository: sofa-framework/SofaPython3
          ref: master
          token: ${{ secrets.PERF_REG_TOKEN }}
          path: SofaPython3

      - name: Get SofaPython3 commit info
        run: |
          cd SofaPython3
          SOFA_PYTHON3_SHA=$(git rev-parse HEAD)
          SOFA_PYTHON3_COMMIT_DATE=$(git show -s --date=format:%Y%m%d --format=%cd $SOFA_PYTHON3_SHA)

          echo "SOFA_PYTHON3_SHA=$SOFA_PYTHON3_SHA" >> $GITHUB_ENV
          echo "SOFA_PYTHON3_COMMIT_DATE=$SOFA_PYTHON3_COMMIT_DATE" >> $GITHUB_ENV

      - name: Launch build of development conda packages of SOFA
        run: |
          sudo apt install curl
          
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERF_REG_TOKEN }}"  \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/sofa-framework/conda-ci/dispatches \
          -d '{"event_type":"build-devel-sofa-all","client_payload":{"sofa_commit_date":"${{ env.SOFA_COMMIT_DATE }}","sofa_commit_hash":"${{ github.sha }}","sofa_python3_commit_hash":"${{ env.SOFA_PYTHON3_SHA }}","sofa_python3_commit_date":"${{ env.SOFA_PYTHON3_COMMIT_DATE }}"}}'
