name: Launch build of development conda packages of SOFA
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'sofa-framework' }}

    steps:
      - name: Launch build of development conda packages of SOFA
        run: |
          sudo apt install curl
          
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERF_REG_TOKEN }}"  \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/sofa-framework/conda-ci/dispatches \
          -d '{"event_type":"build-nightly-sofa","client_payload":{"branch":"master","commit_hash":"${{ github.sha }}"}}'
