name: "CI - Nix"

on:
  push:

jobs:
  nix:
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        #os: [ubuntu, macos]
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      # TODO: the "sofa" account on cachix does not exist yet
      #- uses: cachix/cachix-action@v15
        #with:
          #name: sofa
          #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L
